In [ ]:
1.Write a Python program to convert a list of numeric value into a one-dimensional NumPy array.

In [5]:
import numpy as np
list1=[1,2,3,4,5,6,7,8]
print("The list contents are ",list1)
a=np.array(list1)
print("The array contents are ",a)

The list contents are  [1, 2, 3, 4, 5, 6, 7, 8]
The array contents are  [1 2 3 4 5 6 7 8]


In [ ]:
2.Create a 3x3 matrix with values ranging from 2 to 10.

In [13]:
a=np.arange(2,11).reshape(3,3)
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
3.Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [19]:
a=np.zeros(10)
print("The null vector is ",a)
a[5]=11
print("The vector after updating sixth value is ",a)

The null vector is  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
The vector after updating sixth value is  [  0.   0.   0.   0.   0.  11.   0.   0.   0.   0.]


In [ ]:
4.Write a Python program to create a array with values ranging from 12 to 38.

In [25]:
a=np.arange(12,39,2)
print("Array with value ranging from 12 to 38")
print(a)

Array with value ranging from 12 to 38
[12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [ ]:
5.Write a Python program to reverse an array (first element becomes last).

In [37]:
arr = np.arange(12,30,2)
print("The original array is")
print(arr)
rev = arr[::-1]
print("The reversed array is")
print(rev)

The original array is
[12 14 16 18 20 22 24 26 28]
The reversed array is
[28 26 24 22 20 18 16 14 12]


In [ ]:
6.Write a Python program to an int array converted to a float type.

In [43]:
arr=np.array([1,2,3,4,5])
print("The integer array is")
print(arr)
b=arr.astype(float)
print("The converted float type is")
print(b)

The integer array is
[1 2 3 4 5]
The converted float type is
[ 1.  2.  3.  4.  5.]


In [ ]:
7.Write a Python program to create a 2d array (5x5) with 1 on the border and 0 inside.

In [51]:
arr=np.ones(25).reshape(5,5)
arr[1:4,1:4]=0
print(arr)

[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


In [ ]:
8.Write a Python program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

In [56]:
a=np.arange(2,50,3)
print(a)
print("The total number of elements in array are ",a.size)
print("Length of one array element in bytes ",a.itemsize)
print("Total bytes consumed by elements ",a.nbytes)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]
The total number of elements in array are  16
Length of one array element in bytes  4
Total bytes consumed by elements  64


In [ ]:
9.Write a Python program to create a function cube which cubes all the elements of an array.

In [69]:
c=[]
def cubee(b):
    for x in range (len(b)):
            c.append(b[x]**3)
    return c
a=np.array([1,2,3,4,5,6,7,8])
print("The array elements are ",a)
cubee(a)
cub=np.array(c)
print("The cube of array elements are ",cub)

The array elements are  [1 2 3 4 5 6 7 8]
The cube of array elements are  [  1   8  27  64 125 216 343 512]


In [ ]:
10.Write a Python program to how to add an extra column to an numpy array.

In [91]:
a=np.arange(2,10).reshape(2,4)
print("Fisrt array is ")
print(a)
b=np.arange(10,12).reshape(2,1)
print("Second array is ")
print(b)
c=np.append(a,b,axis=1)
print("The resulting array is ")
print(c)

Fisrt array is 
[[2 3 4 5]
 [6 7 8 9]]
Second array is 
[[10]
 [11]]
The resulting array is 
[[ 2  3  4  5 10]
 [ 6  7  8  9 11]]


In [ ]:
11.Write a Python program to remove the negative values in a numpy array with 0.

In [113]:
a=np.array([2,4,5,-1,6,9,-6,9,-2,-4])
print("The array with negative values is ")
print(a)
for i in range (len(a)):
    if(a[i]<0):
        a[i]=0

print("The array after removing negative values are ")
print(a)

The array with negative values is 
[ 2  4  5 -1  6  9 -6  9 -2 -4]
The array after removing negative values are 
[2 4 5 0 6 9 0 9 0 0]


In [ ]:
12.Create a  one dimensional array with 3 elements. Extend the array by repeating the current elements, 3 times.

In [119]:
a=np.array([1,2,3])
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
13.Write a Python program compare two arrays using numpy.

In [118]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print("Array First ")
print("Array Second ")
print("a>b")
print(np.greater(a,b))
print("a<b")
print(np.less(a,b))
print("a=b")
print(np.equal(a,b))

Array First 
Array Second 
a>b
[False False False False]
a<b
[ True  True  True  True]
a=b
[False False False False]


In [ ]:
14.Write a Python program to find the memory size of a NumPy array.

In [ ]:
Same as question 8

In [ ]:
15.Create a 3x5 array with random elements. Reshape this into 5x3. 

In [86]:
a=np.random.rand(3,5)
print("3*5 array with random elements")
print(a)
print("5*3 array with same elements")
b=a.reshape(5,3)
print(b)

3*5 array with random elements
[[ 0.07113412  0.48490699  0.07690927  0.82941259  0.54734777]
 [ 0.75653534  0.3830057   0.58971384  0.95404086  0.65873117]
 [ 0.96801692  0.8188013   0.26041023  0.18347726  0.75110092]]
5*3 array with same elements
[[ 0.07113412  0.48490699  0.07690927]
 [ 0.82941259  0.54734777  0.75653534]
 [ 0.3830057   0.58971384  0.95404086]
 [ 0.65873117  0.96801692  0.8188013 ]
 [ 0.26041023  0.18347726  0.75110092]]


In [ ]:
16.Write a Python program to create a 3-D array [6x6x6] with ones on diagonals and zeros elsewhere

In [63]:
a=np.eye(6)
b=np.array([a]*6)
print(b.shape)
print(b)

(6, 6, 6)
[[[ 1.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.]
  [ 0.  0.  0.  0.  0.  1.]]

 [[ 1.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.]
  [ 0.  0.  0.  0.  0.  1.]]

 [[ 1.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.]
  [ 0.  0.  0.  0.  0.  1.]]

 [[ 1.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.]
  [ 0.  0.  0.  0.  0.  1.]]

 [[ 1.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.]
  [ 0.  0.  0.  0.  0.  1.]]

 [[ 1.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.]


In [ ]:
17. The following table includes marks of students in various subjects.  Each row corresponds to a student [ Rajesh, Rima, Ram and Joseph]  coulmn correspond to a subject [Maths, Physics, Chemistry, Sociology]

15 . 20 .   25  12
45 .  50 .  50 . 48
8 .    7 .   3 .    2
28 .  32 . 40 .  39

Do the following 
A.
1. FInd the mean, median, mode and standard deviation for marks of each subject
2. What is the minimum and maximum of each subject?
3. Print the subject in  each student good at and poor at ?
4. What is the overall class mean, mode, median and standard deviation

B.
Teacher just announced the marks of English. They are 40, 49, 10 and 35 for eah student.

Re-calculate all subparts of A.

C. A new student joined the class. For the time being, the scores are going to be zero for each student. 

Re-calculate A again with the new student.

D. Print the current score card for the class

In [ ]:
Q.1. FInd the mean, median, mode and standard deviation for marks of each subject

In [52]:
import numpy as np
from scipy import stats
list1=["Maths","Physics","Chemistry","Sociology"]
marks=np.array([[15,20,25,12],[45,50,50,48],[8,7,3,2],[28,32,40,39]])

mean=np.mean(marks,axis=0)
print("The mean for following subjects are :")
for x in range(len(list1)):
        print(list1[x], mean[x])
print("\n")

med=np.median(marks,axis=0)
print("The median of subjects are :")
for x in range(len(list1)):
        print(list1[x], med[x])
print("\n")

m=stats.mode(marks,axis=0)
print("The mode of subjects is :",m[0])
print("\n")

std=np.std(marks,axis=0)
print("The standard deviation of subjects are :")
for x in range(len(list1)):
        print(list1[x], std[x])

The mean for following subjects are :
Maths 24.0
Physics 27.25
Chemistry 29.5
Sociology 25.25


The median of subjects are :
Maths 21.5
Physics 26.0
Chemistry 32.5
Sociology 25.5


The mode of subjects is : [[8 7 3 2]]


The standard deviation of subjects are :
Maths 14.0890028036
Physics 15.8331140336
Chemistry 17.6988700204
Sociology 18.8596792125


In [ ]:
2. What is the minimum and maximum of each subject?

In [29]:
list1=["Maths","Physics","Chemistry","Sociology"]
marks=np.array([[15,20,25,12],[45,50,50,48],[8,7,3,2],[28,32,40,39]])
minimum=np.min(marks,axis=0)
print("The minimum of subjects are :")
for x in range(len(list1)):
        print(list1[x], minimum[x])
print("\n")
maximum=np.max(marks,axis=0)
print("The maximum of subjects are :")
for x in range(len(list1)):
        print(list1[x], maximum[x])

The minimum of subjects are :
Maths 8
Physics 7
Chemistry 3
Sociology 2


The maximum of subjects are :
Maths 45
Physics 50
Chemistry 50
Sociology 48


In [ ]:
3. Print the subject in  each student good at and poor at ?

In [60]:
sub=["maths","physics","chemistry","sociology"]
print("Rajesh is good in %s and bad in %s"%(sub[marks[0].argmax()],sub[marks[0].argmin()]))
print("Rima is good in %s and bad in %s"%(sub[marks[1].argmax()],sub[marks[1].argmin()]))
print("Ram is good in %s and bad in %s"%(sub[marks[2].argmax()],sub[marks[2].argmin()]))
print("Joseph is good in %s and bad in %s"%(sub[marks[3].argmax()],sub[marks[3].argmin()]))

Rajesh is good in chemistry and bad in sociology
Rima is good in physics and bad in maths
Ram is good in maths and bad in sociology
Joseph is good in chemistry and bad in maths


In [ ]:
4. What is the overall class mean, mode, median and standard deviation

In [31]:
mean=np.mean(marks)
print("The mean of overall class is: ",mean)
med=np.median(marks)
print("The median of overall class is: ",med)
m=stats.mode(marks)
print("The mode of overall class is: ",m[0])
std=np.std(marks)
print("The standard deviation of overall class is: ",std)

The mean of overall class is:  26.5
The median of overall class is:  26.5
The mode of overall class is:  [[8 7 3 2]]
The standard deviation of overall class is:  16.8485904455


In [ ]:
B. Teacher just announced the marks of English. They are 40, 49, 10 and 35 for eah student.

In [ ]:
1. FInd the mean, median, mode and standard deviation for marks of each subject

In [38]:
list2=["Maths","Physics","Chemistry","Sociology","English"]
newmarks=np.array([40,49,10,35]).reshape(4,1)
markss=np.append(marks,newmarks,axis=1)
nmean=np.mean(markss,axis=0)
print("The mean for following subjects are :")
for x in range(5):
        print(list2[x], nmean[x])
print("\n")

nmed=np.median(markss,axis=0)
print("The median of subjects are :")
for x in range(len(list2)):
        print(list2[x], nmed[x])
print("\n")

nm=stats.mode(markss,axis=0)
print("The mode of subjects is :",nm[0])
print("\n")

nstd=np.std(markss,axis=0)
print("The standard deviation of subjects are :")
for x in range(len(list2)):
        print(list2[x], nstd[x])

The mean for following subjects are :
Maths 24.0
Physics 27.25
Chemistry 29.5
Sociology 25.25
English 33.5


The median of subjects are :
Maths 21.5
Physics 26.0
Chemistry 32.5
Sociology 25.5
English 37.5


The mode of subjects is : [[ 8  7  3  2 10]]


The standard deviation of subjects are :
Maths 14.0890028036
Physics 15.8331140336
Chemistry 17.6988700204
Sociology 18.8596792125
English 14.4654761415


In [ ]:
2. What is the minimum and maximum of each subject?

In [39]:
minimum=np.min(markss,axis=0)
print("The minimum of subjects are :")
for x in range(len(list2)):
        print(list2[x], minimum[x])
print("\n")
maximum=np.max(markss,axis=0)
print("The maximum of subjects are :")
for x in range(len(list2)):
        print(list2[x], maximum[x])

The minimum of subjects are :
Maths 8
Physics 7
Chemistry 3
Sociology 2
English 10


The maximum of subjects are :
Maths 45
Physics 50
Chemistry 50
Sociology 48
English 49


In [ ]:
3. Print the subject in  each student good at and poor at ?

In [61]:
sub=["maths","physics","chemistry","sociology","English"]
print("Rajesh is good in %s and bad in %s"%(sub[markss[0].argmax()],sub[markss[0].argmin()]))
print("Rima is good in %s and bad in %s"%(sub[markss[1].argmax()],sub[markss[1].argmin()]))
print("Ram is good in %s and bad in %s"%(sub[markss[2].argmax()],sub[markss[2].argmin()]))
print("Joseph is good in %s and bad in %s"%(sub[markss[3].argmax()],sub[markss[3].argmin()]))

Rajesh is good in English and bad in sociology
Rima is good in physics and bad in maths
Ram is good in English and bad in sociology
Joseph is good in chemistry and bad in maths


In [ ]:
4. What is the overall class mean, mode, median and standard deviation

In [40]:
mean=np.mean(markss)
print("The mean of overall class is: ",mean)
med=np.median(markss)
print("The median of overall class is: ",med)
m=stats.mode(markss)
print("The mode of overall class is: ",m[0])
std=np.std(markss)
print("The standard deviation of overall class is: ",std)

The mean of overall class is:  27.9
The median of overall class is:  30.0
The mode of overall class is:  [[ 8  7  3  2 10]]
The standard deviation of overall class is:  16.6370069424


In [ ]:
C. A new student joined the class. For the time being, the scores are going to be zero for each student. 

In [ ]:
1. FInd the mean, median, mode and standard deviation for marks of each subject

In [45]:
newstud=np.array([0,0,0,0,0]).reshape(1,5)
marksss=np.append(markss,newstud,axis=0)
nmean=np.mean(marksss,axis=0)
print("The mean for following subjects are :")
for x in range(len(list2)):
        print(list2[x], nmean[x])
print("\n")

nmed=np.median(marksss,axis=0)
print("The median of subjects are :")
for x in range(len(list2)):
        print(list2[x], nmed[x])
print("\n")

nm=stats.mode(marksss,axis=0)
print("The mode of subjects is :",nm[0])
print("\n")

nstd=np.std(marksss,axis=0)
print("The standard deviation of subjects are :")
for x in range(len(list2)):
        print(list2[x], nstd[x])

The mean for following subjects are :
Maths 19.2
Physics 21.8
Chemistry 23.6
Sociology 20.2
English 26.8


The median of subjects are :
Maths 15.0
Physics 20.0
Chemistry 25.0
Sociology 12.0
English 35.0


The mode of subjects is : [[0 0 0 0 0]]


The standard deviation of subjects are :
Maths 15.8417170787
Physics 17.870646323
Chemistry 19.7443662851
Sociology 19.6611291639
English 18.626862323


In [ ]:
2. What is the minimum and maximum of each subject?

In [46]:
minimum=np.min(marksss,axis=0)
print("The minimum of subjects are :")
for x in range(len(list2)):
        print(list2[x], minimum[x])
print("\n")
maximum=np.max(marksss,axis=0)
print("The maximum of subjects are :")
for x in range(len(list2)):
        print(list2[x], maximum[x])

The minimum of subjects are :
Maths 0
Physics 0
Chemistry 0
Sociology 0
English 0


The maximum of subjects are :
Maths 45
Physics 50
Chemistry 50
Sociology 48
English 49


In [ ]:
3. Print the subject in  each student good at and poor at ?

In [62]:
sub=["maths","physics","chemistry","sociology","English"]
print("Rajesh is good in %s and bad in %s"%(sub[marksss[0].argmax()],sub[marksss[0].argmin()]))
print("Rima is good in %s and bad in %s"%(sub[marksss[1].argmax()],sub[marksss[1].argmin()]))
print("Ram is good in %s and bad in %s"%(sub[marksss[2].argmax()],sub[marksss[2].argmin()]))
print("Joseph is good in %s and bad in %s"%(sub[marksss[3].argmax()],sub[marksss[3].argmin()]))
print("Sunny is good in %s and bad in %s"%(sub[marksss[4].argmax()],sub[marksss[4].argmin()]))

Rajesh is good in English and bad in sociology
Rima is good in physics and bad in maths
Ram is good in English and bad in sociology
Joseph is good in chemistry and bad in maths
Sunny is good in maths and bad in maths


In [ ]:
4. What is the overall class mean, mode, median and standard deviation

In [47]:
mean=np.mean(marksss)
print("The mean of overall class is: ",mean)
med=np.median(marksss)
print("The median of overall class is: ",med)
m=stats.mode(marksss)
print("The mode of overall class is: ",m[0])
std=np.std(marksss)
print("The standard deviation of overall class is: ",std)

The mean of overall class is:  22.32
The median of overall class is:  20.0
The mode of overall class is:  [[0 0 0 0 0]]
The standard deviation of overall class is:  18.6004731123


In [ ]:
D. Print the current score card for the class

In [51]:
print("The marks card for Rajesh is :")
for x in range(len(list2)):
    print(list2[x],marksss[0][x])
print("\n")
print("The marks card for Rima is :")
for x in range(len(list2)):
    print(list2[x],marksss[1][x])
print("\n")
print("The marks card for Ram is :")
for x in range(len(list2)):
    print(list2[x],marksss[2][x])
print("\n")
print("The marks card for Joseph is :")
for x in range(len(list2)):
    print(list2[x],marksss[3][x])

The marks card for Rajesh is :
Maths 15
Physics 20
Chemistry 25
Sociology 12
English 40


The marks card for Rima is :
Maths 45
Physics 50
Chemistry 50
Sociology 48
English 49


The marks card for Ram is :
Maths 8
Physics 7
Chemistry 3
Sociology 2
English 10


The marks card for Joseph is :
Maths 28
Physics 32
Chemistry 40
Sociology 39
English 35
