In [16]:
#Q1. Create a vector or array of 100 elements. Its 50th value should be    50.0 and other values should be 0.0 (1 mark)

import numpy as np
a=np.zeros(100)
a[49]=50
print("The array with 50th value as 50 and rest values as 0.0 is ")
print(a)

The array with 50th value as 50 and rest values as 0.0 is 
[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.  50.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]


In [4]:
#Q2. Create a vector or array of 100 elements. Its 50th value should be    10.0 and other values should be 1.0 (1 mark)

b=np.ones(100)
b[49]=10
print("The array with 50th value as 10 and rest values as 1.0 is ")
print(b)

[  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.  10.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]


In [9]:
#Q3. Create a  vector or array whose values are from 3, 30 (1 mark)

c=np.arange(3,31)
print("Vector or array whose values are from 3,30 is ")
print(c)

Vector or array whose values are from 3,30 is 
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
 28 29 30]


In [12]:
#Q4. X = (1,2,3,4,5).  Reverse and print X (1 mark)

x=(1,2,3,4,5)
print("The original order is ")
print(x)
y=x[::-1]
print("The reversed order is ")
print(y)

The original order is 
(1, 2, 3, 4, 5)
The reversed order is 
(5, 4, 3, 2, 1)


In [17]:
#Q5. Create a 5x 5 matrix and values should be from 0 to 24 (1 mark)

mat=np.arange(0,25).reshape(5,5)
print("A 5x 5 matrix and values from 0 to 24 is ")
print(mat)

A 5x 5 matrix and values from 0 to 24 is 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
#Q6. Consider the following  matrix A1 and A2   (9 marks)


       A1 :
             1        3       0

             2        1        1

             3        4         0

       A2 :
             3        4         6
   
             2        1          3

             1        2          8

In [21]:
#Qa) Find min. max of the values for A1 and A2
a1=np.array([[1,3,0],[2,1,1],[3,4,0]])
a2=np.array([[3,4,6],[2,1,3],[1,2,8]])
mina1=a1.min()
print("Minimum of a1 is ",mina1)
mina2=a2.min()
print("Minimum of a2 is ",mina2)
maxa1=a1.max()
print("Maximum of a1 is ",maxa1)
maxa2=a2.max()
print("Maximum of a2 is ",maxa2)


Minimum of a1 is  0
Minimum of a2 is  1
Maximum of a1 is  4
Maximum of a2 is  8


In [18]:
#Qb) Find the mean value for A1 and A2

mean=np.mean(a1)
print("The mean value for a1 is ",mean)
mean1=np.mean(a2)
print("The mean values for a2 is ",mean1)

The mean value for a1 is  1.66666666667
The mean values for a2 is  3.33333333333


In [22]:
#Qc) Make the values below the diagonal as 0.0 for A1

print(a1)
newa3=a1
newa3[1,0]=0
newa3[2,0]=0
newa3[2,1]=0
print("New Matrix")
print(newa3)

[[1 3 0]
 [2 1 1]
 [3 4 0]]
New Matrix
[[1 3 0]
 [0 1 1]
 [0 0 0]]


In [37]:
#Qd) Multiply A1 and A2

a1=np.array([[1,3,0],[2,1,1],[3,4,0]])
a2=np.array([[3,4,6],[2,1,3],[1,2,8]])
result=np.zeros(9).reshape(3,3)
for i in range(len(a1)):
    for j in range(len(a2[0])):
         for k in range(len(a2)):
            result[i][j] += a1[i][k] * a2[k][j]
            
print("The resultant matrix is ")
for r in result:
    print(r)

The resultant matrix is 
[  9.   7.  15.]
[  9.  11.  23.]
[ 17.  16.  30.]


In [40]:
#Qe) What are the common values between A1 and A2

import numpy as np
a1=np.array([1,3,0,2,1,1,3,4,0]).reshape(3,3)
a2=np.array([3,4,6,2,1,3,1,2,8]).reshape(3,3)
print("Common values between two arrays:")
print(np.intersect1d(a1,a2))

Common values between two arrays:
[1 2 3 4]


In [41]:
#Qf) Swap first and 3rd rows of A1

new=a1
temppp=new[0]
new[0]=new[2]
new[2]=temppp
print(new)

[[3 4 0]
 [2 1 1]
 [3 4 0]]


In [48]:
#Qg) What is the  mosft frequent numbers from A1 and A2

a1=np.array([1,3,0,2,1,1,3,4,0]).reshape(3,3)
counts=np.bincount(a1)
print(np.argmax(counts))
a2=np.array([3,4,6,2,1,3,1,2,8]).reshape(3,3)
counts1=np.bincount(a2)
print(np.argmax(counts1))


ValueError: object too deep for desired array

In [52]:
#Qh) Add a column to A1 with values 1 1 1 

newcol=np.ones(3).reshape(3,1)
newmat=np.append(a1,newcol,axis=1)
print("A1 value after adding an extra column")
print(newmat)

A1 value after adding an extra column
[[ 3.  4.  0.  1.]
 [ 2.  1.  1.  1.]
 [ 3.  4.  0.  1.]]


In [53]:
#Qi) Add a row to A2 with 2 2 2

newrow=np.full([1,3],2)
newwmat=np.append(a2,newrow,axis=0)
print("A2 value after adding an extra row")
print(newwmat)

A2 value after adding an extra row
[[3 4 6]
 [2 1 3]
 [1 2 8]
 [2 2 2]]


In [30]:
#Q7. Write a function for matrix multiplications and additions. Use A1 and A2 to test.
def multi(a1,a2,resultmul):
    for i in range(len(a1)):
        for j in range(len(a2[0])):
            for k in range(len(a2)):
                resultmul[i][j]+= a1[i][k] * a2[k][j]
    for r in resultmul:
        print(r)
        
def addition(a1,a2,resultadd):
    for i in range(len(a1)):
        for j in range(len(a2)):
            resultadd[i][j]=a1[i][j]+a2[i][j]
    for d in resultadd:
        print(d)
                
a1=np.array([[1,3,0],[2,1,1],[3,4,0]])
a2=np.array([[3,4,6],[2,1,3],[1,2,8]])
resultmul=np.zeros(9).reshape(3,3)
resultadd=np.zeros(9).reshape(3,3)
print("1.Multiplication")
print("2.Addition")
ch=int(input("Enter your choice "))
if(ch==1):
    print("The multiplicaton result is ")
    multi(a1,a2,resultmul)
if(ch==2):
    print("The additon result is ")
    addition(a1,a2,resultadd)

1.Multiplication
2.Addition
Enter your choice 2
The additon result is 
[ 4.  7.  6.]
[ 4.  2.  4.]
[ 4.  6.  8.]


In [13]:
#Q8. Write a bubble sort program with normal Python  for 10 floating point numbers

def bubble(num):
    n = len(num)
    for i in range(n):
        for j in range(0, n-i-1):
            if num[j] > num[j+1] :
                num[j], num[j+1] = num[j+1], num[j]
                

num=[10.0,11.5,2.0,3.0,17.6,22.8,22.6,21.5,18.9,1.1]
bubble(num)
print("sorted array is ")
for i in range (len(num)):
    print("%.2f "%num[i])


sorted array is 
1.10 
2.00 
3.00 
10.00 
11.50 
17.60 
18.90 
21.50 
22.60 
22.80 
